-- Start transaction
START TRANSACTION;

-- Step 1: Create the new normalized tables
CREATE TABLE IF NOT EXISTS tb_domains (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    hostname VARCHAR(255),

    CONSTRAINT tb_domains_pk PRIMARY KEY (id),
    CONSTRAINT tb_domains_hostname_un UNIQUE(hostname)
);

CREATE TABLE IF NOT EXISTS tb_pages (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    path      VARCHAR(255),
    domain_id BIGINT,

    CONSTRAINT tb_pages_pk PRIMARY KEY (id),
    CONSTRAINT tb_pages_path_un UNIQUE(domain_id, path),
    CONSTRAINT tb_pages_domain_fk FOREIGN KEY (domain_id) REFERENCES tb_domains(id)
);

-- Step 2: Add the new foreign key column to tb_views
ALTER TABLE tb_views 
    ADD COLUMN page_id BIGINT;

-- Step 3: Extract and insert unique domains from existing URLs
INSERT INTO tb_domains (hostname)
SELECT DISTINCT 
    LOWER(
        REGEXP_REPLACE(
            REGEXP_REPLACE(
                -- Remove fragment before extracting domain
                REGEXP_REPLACE("page", '#.*$', ''),
                '^https?://',
                ''
            ),
            '^([^/]+).*$',
            '\1'
        )
    ) AS hostname
FROM tb_views 
WHERE "page" IS NOT NULL 
    AND "page" != ''
ON CONFLICT (hostname) DO NOTHING;

-- Step 4: Extract and insert unique pages with their domain references
INSERT INTO tb_pages (path, domain_id)
SELECT DISTINCT 
    LOWER(
        COALESCE(
            NULLIF(
                '/' || REGEXP_REPLACE(
                    REGEXP_REPLACE(
                        -- Remove fragment before extracting path
                        REGEXP_REPLACE(v."page", '#.*$', ''),
                        '^https?://[^/]+',
                        ''
                    ),
                    '^/?',
                    ''
                ),
                '/'
            ),
            '/'
        )
    ) AS path,
    d.id AS domain_id
FROM tb_views v
INNER JOIN tb_domains d ON LOWER(
    REGEXP_REPLACE(
        REGEXP_REPLACE(
            -- Remove fragment before extracting domain
            REGEXP_REPLACE(v."page", '#.*$', ''),
            '^https?://',
            ''
        ),
        '^([^/]+).*$',
        '\1'
    )
) = d.hostname
ON CONFLICT (domain_id, path) DO NOTHING;

-- Step 5: Update tb_views to set the page_id foreign key
UPDATE tb_views v
SET page_id = p.id
FROM tb_pages p
INNER JOIN tb_domains d ON p.domain_id = d.id
WHERE LOWER(
    REGEXP_REPLACE(
        REGEXP_REPLACE(
            -- Remove fragment before extracting domain
            REGEXP_REPLACE(v."page", '#.*$', ''),
            '^https?://',
            ''
        ),
        '^([^/]+).*$',
        '\1'
    )
) = d.hostname
    AND LOWER(
        COALESCE(
            NULLIF(
                '/' || REGEXP_REPLACE(
                    REGEXP_REPLACE(
                        -- Remove fragment before extracting path
                        REGEXP_REPLACE(v."page", '#.*$', ''),
                        '^https?://[^/]+',
                        ''
                    ),
                    '^/?',
                    ''
                ),
                '/'
            ),
            '/'
        )
    ) = p.path
    AND v.page_id IS NULL;

-- Step 6: Add foreign key constraint after data migration
ALTER TABLE tb_views 
    ADD CONSTRAINT tb_views_page_fk FOREIGN KEY (page_id) REFERENCES tb_pages(id),
    DROP COLUMN "page";

-- Commit transaction
COMMIT;