DO $$
    BEGIN
        -- Create the visitas table
        CREATE TABLE IF NOT EXISTS tb_views (
            id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
            "length"          BIGINT,
            access_timestamp  TIMESTAMP(6),
            end_timestamp     TIMESTAMP(6),
            "page"            VARCHAR(255),
            referer           VARCHAR(255),
            user_agent        VARCHAR(255),
            user_id           VARCHAR(255),
            tab_id            VARCHAR(255),
            screen_resolution VARCHAR(255), 
            timezone          VARCHAR(255), 

            CONSTRAINT tb_views_pk PRIMARY KEY (id)
        );
            
        IF EXISTS 
            (
                SELECT 1 
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'visitas'
            ) 
        THEN
            -- Copy previous content
            INSERT INTO tb_views ("length", access_timestamp, end_timestamp, timezone, "page", referer, user_agent)
            SELECT duracao, dataAcesso, dataSaida, ip, pagina, referer, userAgent FROM visitas;

            DROP TABLE visitas;
        END IF;

        IF EXISTS 
            (
                SELECT 1 
                FROM pg_roles 
                WHERE rolname = 'visita_user'
            ) THEN
            -- Grant all privileges on the table to the application user
            GRANT ALL PRIVILEGES ON TABLE tb_views TO visita_user;
            GRANT USAGE, SELECT ON SEQUENCE tb_views_id_seq TO visita_user;
        END IF;
    END
$$;